spring:
  freemarker:
    charset: UTF-8
    settings:
      # default charset for string?url()
      url_escaping_charset: UTF-8
      # no auto commify
      number_format: 0.#######

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - configprops

---
spring:
  config:
    activate:
      on-profile: default
logging.level:
  me.geso.blog3.dao: DEBUG
spring:
  freemarker:
    template-loader-path: file:src/main/resources/templates/
