management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - configprops

---
spring:
  config:
    activate:
      on-profile: default

logging.level:
  blog3.dao: DEBUG
