name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-check:
    name: Lint and Check
    runs-on: ubuntu-latest

    steps:
      # リポジトリをクローン
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node.js 環境をセットアップ
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # 依存関係をインストール
      - name: Install dependencies
        run: bun install

      # コードスタイルチェック (Prettier)
      - name: Run Prettier
        run: bunx prettier --check .

      # 静的解析 (ESLint)
      - name: Run ESLint
        run: bunx eslint .

      # 型チェック (SvelteKit)
      - name: Run TypeScript and SvelteKit Check
        run: bun run check

      # テスト
      - name: Run test suite
        run: bun run test

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
      # リポジトリをクローン
      - name: Checkout repository
        uses: actions/checkout@v4

      # Docker ビルドを実行
      - name: Build Docker image
        run: docker build -t blog3-app .
