# https://efcl.info/2023/05/28/rss-to-twitter/
name: rss-to-twitter
on:
  schedule:
    # every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  twitter:
    runs-on: ubuntu-latest
    steps:
      - uses: azu/rss-to-twitter@v1
        with:
          # RSS feed URL
          RSS_URL: 'https://blog.64p.org/feed'
          TWEET_TEMPLATE: 'ブログを書いたよ: "%title%" %url%'
          UPDATE_WITHIN_MINUTES: 15 # for workflow_dispatch
          TWITTER_APIKEY: ${{ secrets.TWITTER_APIKEY }}
          TWITTER_APIKEY_SECRET: ${{ secrets.TWITTER_APIKEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
