name: Docker push(Sacloud)

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@327cd5a69de6c009b9ce71bce8395f28e651bf99
        with:
          registry: tokuhirom-priv.sakuracr.jp
          username: uploader
          password: ${{ secrets.SACLOUD_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build docker image
        run: docker build -t tokuhirom-priv.sakuracr.jp/tokuhirom/blog3 .

      # Push the image
      - name: Build and push Docker image
        run: docker push tokuhirom-priv.sakuracr.jp/tokuhirom/blog3:latest
