name: Docker push(Sacloud)

on:
  push:
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry docker hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@7ca345011ac4304463197fac0e56eab1bc7e6af0
        with:
          registry: tokuhirom-priv.sakuracr.jp
          username: uploader
          password: ${{ secrets.SACLOUD_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build docker image
        run: ./gradlew bootBuildImage --imageName=tokuhirom-priv.sakuracr.jp/tokuhirom/blog3

      # Push the image
      - name: Build and push Docker image
        run: docker push tokuhirom-priv.sakuracr.jp/tokuhirom/blog3:latest
